export const INSERT_EXTRA_COLUMNS_AFTER_REMARK = 11;

export const STATUS_COLOR_MAP = {
  h: "orange",
  a: "green",
  p: "blue",
  r: "red",
} as const;

export type StatusType = keyof typeof STATUS_COLOR_MAP;

export const CheckBoxNames = [
  "Party Group",
  "Order Date",
  "Lot No.",
  "Grade",
  "Subgrade",
  "Cops/Cheese",
  "Design",
  "Color",
  "Shade",
  "Ends",
  "Width",
  "Length",
];

export const orderData = {
  company_name: "Bailey LLC",
  order_no: "000001",
  order_ref_no: "Or78945",
  party_group: "Jay Ambe",
  party_name: "Rahul Patel",
  address: "Akshya Nagar, Ahmedabad",
  item_name: "Tv",
  lot_no: "874569",
  grade: "A",
  subgrade: "AB",
  pieces_box: "2",
  quantity: "2 kg",
  cops_cheese: "20",
  rate: "5",
  remark: "Lorem Ipsum",
  design: "Round",
  color: "Red",
  shade: "Light",
  ends: "5",
  width: "400",
  length: "500",
  status: "Pending",
};

export const data = [
  {
    sr_no: 1,
    order_no: "O00001",
    billing_party: "Bailey LLC",
    order_ref_no: "Or78945",
    party_group: "Akshya Nagar..",
    party_name: "Rahul Patel",
    address: "Akshya Nagar..",
    lot_no: "874569",
    grade: "A",
    subgrade: "Ab",
    item_name: "Tv",
    pieces_box: "2",
    quantity: "2 kg",
    cops_cheese: "20",
    rate: "5",
    design: "Round",
    color: "Red",
    shade: "Light",
    ends: "5",
    width: "400",
    length: "500",
    status: "Hold",
  },
  {
    sr_no: 2,
    order_no: "O00002",
    billing_party: "Ryan-Gibson",
    order_ref_no: "Or32105",
    party_group: "Jay Ambe Nagar..",
    party_name: "Ronak Patel",
    address: "Jay Ambe Nagar..",
    lot_no: "258741",
    grade: "B",
    subgrade: "Ba",
    item_name: "Cctv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "4",
    design: "Round",
    color: "White",
    shade: "Light",
    ends: "10",
    width: "600",
    length: "600",
    status: "Pending",
  },
  {
    sr_no: 3,
    order_no: "O00003",
    billing_party: "Reyon",
    order_ref_no: "Or54126",
    party_group: "Iscon char rasta..",
    party_name: "Chintan Sharma",
    address: "Iscon char rasta..",
    lot_no: "987456",
    grade: "A",
    subgrade: "Ab",
    item_name: "Fridge",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "2",
    design: "Square",
    color: "Black",
    shade: "Dark",
    ends: "100",
    width: "300",
    length: "700",
    status: "Pending",
  },
  {
    sr_no: 4,
    order_no: "O00004",
    billing_party: "Ishani Pvt.Ltd",
    order_ref_no: "Or65412",
    party_group: "Neharunagar 1st..",
    party_name: "Jay Patel",
    address: "Neharunagar 1st..",
    lot_no: "321456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Lidht",
    pieces_box: "4",
    quantity: "4 kg",
    cops_cheese: "40",
    rate: "3",
    design: "Square",
    color: "Yellow",
    shade: "Light",
    ends: "200",
    width: "900",
    length: "900",
    status: "Pending",
  },
  {
    sr_no: 5,
    order_no: "O00005",
    billing_party: "Ramanandi pvt. ltd",
    order_ref_no: "Or98745",
    party_group: "Neharunagar 1st..",
    party_name: "Vasu Patel",
    address: "Neharunagar 1st..",
    lot_no: "987456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Cctv",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "1",
    design: "Round",
    color: "Yellow",
    shade: "Dark",
    ends: "50",
    width: "400",
    length: "500",
    status: "Approved",
  },
  {
    sr_no: 6,
    order_no: "O00006",
    billing_party: "Bauch-Weber",
    order_ref_no: "Or36521",
    party_group: "Neharunagar 1st..",
    party_name: "Akash Patel",
    address: "Neharunagar 1st..",
    lot_no: "654123",
    grade: "A",
    subgrade: "Ab",
    item_name: "Cctv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "4",
    design: "Round",
    color: "White",
    shade: "Light",
    ends: "150",
    width: "500",
    length: "600",
    status: "Approved",
  },
  {
    sr_no: 7,
    order_no: "O00007",
    billing_party: "Shree Ram",
    order_ref_no: "Or45236",
    party_group: "Iscon char rasta..",
    party_name: "Hiren Patel",
    address: "Iscon char rasta..",
    lot_no: "321456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Tv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "2",
    design: "Round",
    color: "Black",
    shade: "Dark",
    ends: "40",
    width: "400",
    length: "500",
    status: "Approved",
  },
  {
    sr_no: 8,
    order_no: "O00008",
    billing_party: "Sunil Sharma",
    order_ref_no: "Or69584",
    party_group: "Jay Ambe Nagar..",
    party_name: "Sunil Sharma",
    address: "Jay Ambe Nagar..",
    lot_no: "014523",
    grade: "C",
    subgrade: "Cd",
    item_name: "Light",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "3",
    design: "Round",
    color: "White",
    shade: "Dark",
    ends: "100",
    width: "500",
    length: "600",
    status: "Approved",
  },
  {
    sr_no: 9,
    order_no: "O00009",
    billing_party: "Bednar and Sons",
    order_ref_no: "Or65847",
    party_group: "Moti Civil",
    party_name: "Kaushik Sharma",
    address: "Moti Civil",
    lot_no: "963852",
    grade: "C",
    subgrade: "Cd",
    item_name: "Fridge",
    pieces_box: "4",
    quantity: "4 kg",
    cops_cheese: "40",
    rate: "1",
    design: "Square",
    color: "Red",
    shade: "Light",
    ends: "80",
    width: "600",
    length: "700",
    status: "Rejected",
  },
  {
    sr_no: 10,
    order_no: "O00010",
    billing_party: "SA Auto",
    order_ref_no: "Or69584",
    party_group: "Akshya Nagar..",
    party_name: "Parth Patel",
    address: "Akshya Nagar..",
    lot_no: "741852",
    grade: "B",
    subgrade: "Bc",
    item_name: "Tv",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "3",
    design: "Square",
    color: "Red",
    shade: "Light",
    ends: "50",
    width: "800",
    length: "900",
    status: "Rejected",
  },
  {
    sr_no: 11,
    order_no: "O00011",
    billing_party: "Bailey LLC",
    order_ref_no: "Or78945",
    party_group: "Akshya Nagar..",
    party_name: "Rahul Patel",
    address: "Akshya Nagar..",
    lot_no: "874569",
    grade: "A",
    subgrade: "Ab",
    item_name: "Tv",
    pieces_box: "2",
    quantity: "2 kg",
    cops_cheese: "20",
    rate: "5",
    design: "Round",
    color: "Red",
    shade: "Light",
    ends: "5",
    width: "400",
    length: "500",
    status: "Pending",
  },
  {
    sr_no: 12,
    order_no: "O00012",
    billing_party: "Ryan-Gibson",
    order_ref_no: "Or32105",
    party_group: "Jay Ambe Nagar..",
    party_name: "Ronak Patel",
    address: "Jay Ambe Nagar..",
    lot_no: "258741",
    grade: "B",
    subgrade: "Ba",
    item_name: "Cctv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "4",
    design: "Round",
    color: "White",
    shade: "Light",
    ends: "10",
    width: "600",
    length: "600",
    status: "Pending",
  },
  {
    sr_no: 13,
    order_no: "O00013",
    billing_party: "Reyon",
    order_ref_no: "Or54126",
    party_group: "Iscon char rasta..",
    party_name: "Chintan Sharma",
    address: "Iscon char rasta..",
    lot_no: "987456",
    grade: "A",
    subgrade: "Ab",
    item_name: "Fridge",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "2",
    design: "Square",
    color: "Black",
    shade: "Dark",
    ends: "100",
    width: "300",
    length: "700",
    status: "Pending",
  },
  {
    sr_no: 14,
    order_no: "O00014",
    billing_party: "Ishani Pvt.Ltd",
    order_ref_no: "Or65412",
    party_group: "Neharunagar 1st..",
    party_name: "Jay Patel",
    address: "Neharunagar 1st..",
    lot_no: "321456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Lidht",
    pieces_box: "4",
    quantity: "4 kg",
    cops_cheese: "40",
    rate: "3",
    design: "Square",
    color: "Yellow",
    shade: "Light",
    ends: "200",
    width: "900",
    length: "900",
    status: "Pending",
  },
  {
    sr_no: 15,
    order_no: "O00015",
    billing_party: "Ramanandi pvt. ltd",
    order_ref_no: "Or98745",
    party_group: "Neharunagar 1st..",
    party_name: "Vasu Patel",
    address: "Neharunagar 1st..",
    lot_no: "987456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Cctv",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "1",
    design: "Round",
    color: "Yellow",
    shade: "Dark",
    ends: "50",
    width: "400",
    length: "500",
    status: "Approved",
  },
  {
    sr_no: 16,
    order_no: "O00016",
    billing_party: "Bauch-Weber",
    order_ref_no: "Or36521",
    party_group: "Neharunagar 1st..",
    party_name: "Akash Patel",
    address: "Neharunagar 1st..",
    lot_no: "654123",
    grade: "A",
    subgrade: "Ab",
    item_name: "Cctv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "4",
    design: "Round",
    color: "White",
    shade: "Light",
    ends: "150",
    width: "500",
    length: "600",
    status: "Approved",
  },
  {
    sr_no: 17,
    order_no: "O00017",
    billing_party: "Shree Ram",
    order_ref_no: "Or45236",
    party_group: "Iscon char rasta..",
    party_name: "Hiren Patel",
    address: "Iscon char rasta..",
    lot_no: "321456",
    grade: "C",
    subgrade: "Cd",
    item_name: "Tv",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "2",
    design: "Round",
    color: "Black",
    shade: "Dark",
    ends: "40",
    width: "400",
    length: "500",
    status: "Approved",
  },
  {
    sr_no: 18,
    order_no: "O00018",
    billing_party: "Sunil Sharma",
    order_ref_no: "Or69584",
    party_group: "Jay Ambe Nagar..",
    party_name: "Sunil Sharma",
    address: "Jay Ambe Nagar..",
    lot_no: "014523",
    grade: "C",
    subgrade: "Cd",
    item_name: "Light",
    pieces_box: "1",
    quantity: "1 kg",
    cops_cheese: "10",
    rate: "3",
    design: "Round",
    color: "White",
    shade: "Dark",
    ends: "100",
    width: "500",
    length: "600",
    status: "Approved",
  },
  {
    sr_no: 19,
    order_no: "O00019",
    billing_party: "Bednar and Sons",
    order_ref_no: "Or65847",
    party_group: "Moti Civil",
    party_name: "Kaushik Sharma",
    address: "Moti Civil",
    lot_no: "963852",
    grade: "C",
    subgrade: "Cd",
    item_name: "Fridge",
    pieces_box: "4",
    quantity: "4 kg",
    cops_cheese: "40",
    rate: "1",
    design: "Square",
    color: "Red",
    shade: "Light",
    ends: "80",
    width: "600",
    length: "700",
    status: "Rejected",
  },
  {
    sr_no: 20,
    order_no: "O00020",
    billing_party: "SA Auto",
    order_ref_no: "Or69584",
    party_group: "Akshya Nagar..",
    party_name: "Parth Patel",
    address: "Akshya Nagar..",
    lot_no: "741852",
    grade: "B",
    subgrade: "Bc",
    item_name: "Tv",
    pieces_box: "3",
    quantity: "3 kg",
    cops_cheese: "30",
    rate: "3",
    design: "Square",
    color: "Red",
    shade: "Light",
    ends: "50",
    width: "800",
    length: "900",
    status: "Rejected",
  },
];

export const detailItems = [
  { label: "Order Ref No.", value: orderData.order_ref_no ?? "" },
  { label: "Party Group", value: orderData.party_group ?? "" },
  { label: "Party Name", value: orderData.party_name ?? "" },
  { label: "Address", value: orderData.address ?? "" },
  { label: "Item Name", value: orderData.item_name ?? "" },
  { label: "Lot No.", value: orderData.lot_no ?? "" },
  { label: "Grade", value: orderData.grade ?? "" },
  { label: "Subgrade", value: orderData.subgrade ?? "" },
  { label: "Piece/Box", value: orderData.pieces_box ?? "" },
  { label: "Quantity (in Kgs.)", value: orderData.quantity ?? "" },
  { label: "Cops/ Cheese", value: orderData.cops_cheese ?? "" },
  { label: "Rate", value: orderData.rate ?? "" },
  { label: "Remark", value: orderData.remark ?? "" },
  { label: "Design", value: orderData.design ?? "" },
  { label: "Color", value: orderData.color ?? "" },
  { label: "Shade", value: orderData.shade ?? "" },
  { label: "Ends", value: orderData.ends ?? "" },
  { label: "Width", value: orderData.width ?? "" },
  { label: "Length", value: orderData.length ?? "", full: true },
];
