import type { DocumentRow } from "./types";

export const documentRows: DocumentRow[] = [
  {
    key: 1,
    sr: 1,
    docNo: "D00001",
    date: "01/04/2024",
    billingParty: "Bailey LLC",
    type: "Credit Note",
    amount: 200,
    document: "xxx.png",
  },
  {
    key: 2,
    sr: 2,
    docNo: "D00002",
    date: "19/04/2024",
    billingParty: "Ryan-Gibson",
    type: "Debit Note",
    amount: 1000,
    document: "xxx.xlsx",
  },
  {
    key: 3,
    sr: 3,
    docNo: "D00003",
    date: "22/06/2024",
    billingParty: "Reyon",
    type: "Sales Return",
    amount: 800,
    document: "xxx.xlsx",
  },
  {
    key: 4,
    sr: 4,
    docNo: "D00004",
    date: "24/06/2024",
    billingParty: "Ishani Pvt. Ltd",
    type: "Credit Note",
    amount: 2000,
    document: "xxx.xlsx",
  },
  {
    key: 5,
    sr: 5,
    docNo: "D00005",
    date: "24/06/2025",
    billingParty: "Ramanandi Pvt. Ltd.",
    type: "Credit Note",
    amount: 500,
    document: "xxx.xlsx",
  },
  {
    key: 6,
    sr: 6,
    docNo: "D00006",
    date: "09/04/2024",
    billingParty: "Bauch-Weber",
    type: "Sales Return",
    amount: 7000,
    document: "xxx.xlsx",
  },
  {
    key: 7,
    sr: 7,
    docNo: "D00007",
    date: "13/06/2025",
    billingParty: "Shree Ram",
    type: "Debit Note",
    amount: 7652,
    document: "xxx.xlsx",
  },
  {
    key: 8,
    sr: 8,
    docNo: "D00008",
    date: "14/06/2025",
    billingParty: "Sunil Sharma",
    type: "Credit Note",
    amount: 4520,
    document: "xxx.xlsx",
  },
  {
    key: 9,
    sr: 9,
    docNo: "D00009",
    date: "18/06/2025",
    billingParty: "Bednar and Sons",
    type: "Sales Return",
    amount: 4254,
    document: "xxx.xlsx",
  },
  {
    key: 10,
    sr: 10,
    docNo: "D00010",
    date: "20/06/2025",
    billingParty: "SA Auto",
    type: "Credit Note",
    amount: 452,
    document: "xxx.xlsx",
  },
];

export const dealerOption = [
  { value: "Tejas", label: "Tejas" },
  { value: "Sandip", label: "Sandip" },
  { value: "Divyesh", label: "Divyesh" },
];

export const statusOption = [
  { value: "Active", label: "Active" },
  { value: "Inactive", label: "Inactive" },
];
