import type { ColumnOption, DeliveryOrderType } from "@repo/ui";

export const deliveryOrderColumnOptions: ColumnOption[] = [
  { key: "party_group", label: "Party Group" },
  { key: "lot_no", label: "Lot No." },
  { key: "order_quantity", label: "Order Quantity(in Kgs.)" },
  { key: "sale_quantity", label: "Sale Quantity(in Kgs.)" },
  { key: "do_quantity", label: "Do Quantity(in Kgs.)" },
  { key: "balance_quantity", label: "Balance Quantity(in Kgs.)" },
  { key: "payment_terms", label: "Payment Terms" },
  { key: "list_price", label: "List Price" },
  { key: "basic_rate", label: "Basic Rate" },
  { key: "net_rate", label: "Net Rate" },
  { key: "advanced_received", label: "Advanced Received" },
  { key: "grade", label: "Grade" },
  { key: "subgrade", label: "Subgrade" },
  { key: "cops_cheese", label: "Cops/Cheese" },
  { key: "remark", label: "Remark" },
  { key: "order_date", label: "Order Date" },
  { key: "d_o_date_time", label: "D.O. Date & Time" },
];
export const deliveryOrdersData: DeliveryOrderType[] = [
  {
    sr_no: 1,
    code: "D00001",
    order_no: "O00001",
    party_name: "Rahul Patel",
    item_name: "Tv",
    quantity: "2 Kg",
    address: "Ahmedabad",
    gst: "GS034089",
    rate: "5",
    pieces_box: "2",
    status: "Pending",
  },
  {
    sr_no: 2,
    code: "D00002",
    order_no: "O00003",
    party_name: "Ronak Patel",
    item_name: "Cctv",
    quantity: "1 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "4",
    pieces_box: "1",
    status: "Pending",
  },
  {
    sr_no: 3,
    code: "D00003",
    order_no: "O00003",
    party_name: "Chintan Sharma",
    item_name: "Fridge",
    quantity: "3 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "2",
    pieces_box: "3",
    status: "Pending",
  },
  {
    sr_no: 4,
    code: "D00004",
    order_no: "O00004",
    party_name: "Jay Patel",
    item_name: "Light",
    quantity: "4 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "3",
    pieces_box: "4",
    status: "Pending",
  },
  {
    sr_no: 5,
    code: "D00005",
    order_no: "O00005",
    party_name: "Vasu Patel",
    item_name: "Cctv",
    quantity: "3 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "1",
    pieces_box: "3",
    status: "Approved",
  },
  {
    sr_no: 6,
    code: "D00006",
    order_no: "O00006",
    party_name: "Akash Patel",
    item_name: "Cctv",
    quantity: "1 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "4",
    pieces_box: "1",
    status: "Approved",
  },
  {
    sr_no: 7,
    code: "D00007",
    order_no: "O00007",
    party_name: "Hiren Patel",
    item_name: "Tv",
    quantity: "1 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "2",
    pieces_box: "1",
    status: "Approved",
  },
  {
    sr_no: 8,
    code: "D00008",
    order_no: "O00008",
    party_name: "Sunil Sharma",
    item_name: "Light",
    quantity: "1 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "3",
    pieces_box: "1",
    status: "Approved",
  },
  {
    sr_no: 9,
    code: "D00009",
    order_no: "O00009",
    party_name: "Kaushik Sharma",
    item_name: "Fridge",
    quantity: "4 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "1",
    pieces_box: "4",
    status: "Rejected",
  },
  {
    sr_no: 10,
    code: "D00010",
    order_no: "O00010",
    party_name: "Parth Patel",
    item_name: "Tv",
    quantity: "3 Kg",
    address: "Ahmedabad",
    gst: "GS078945",
    rate: "3",
    pieces_box: "3",
    status: "Rejected",
  },
];
